# Use this file like this:
#   conda env create -f requirements.yml
# Then (on Windows machines) activate the environment like this:
#   activate im_mdata_report_env
name: EPOS_DCAT_AP
dependencies:
 - python=3.6.1
 - pytest=3.2.1
 - pyyaml=3.12
 - pip:
   - rdflib

